### ISSUE TITLE
정리를 정말 잘 해주셨는데 제가 교안처럼 사용해도 될까요...?

### ISSUE THREAD

**Issue by ZeroCho** [yangareum1818/data-structure#3]
8월 중순에 인프런에 강의 출시하면 공짜로 드리도록 하겠습니다!(인프런 강의에만 있는 레드블랙트리 등의 추가 자료구조가 있습니다)

**Comment by eillen-yang** [comment]
네 ! 사용하셔도됩니다 ! 감사합니다 ! 마지막 넓이, 깊이 탐색과 트리순회도 열심히 공부해 보겠습니다 !

**Comment by ZeroCho** [comment]
이메일 알려주시면 강의넣어드릴게요!

**Comment by eillen-yang** [comment]
> 이메일 알려주시면 강의넣어드릴게요!

인프런 로그인할 때, 이메일 알려드리면 될까요 ?
정리한 원본파일도 필요하시면 말씀해주시면 보내드릴게요 !

princess4001@naver.com

**Comment by ZeroCho** [comment]
강의 넣어드렸습니다!
